[package]
name = "rust-tesseract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptess = "0.13.2"
image = "0.24.1"
image-convert = "0.11.3"